name: top_snackbar
description: A custom top snackbar widget for Flutter
version: 0.0.1
homepage: https://github.com/deb-sahu/top-snackbar

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
