name: top_snackbar
description: A minimal Flutter library tailored for top snackbar notifications. Highly customizable and easy-to-use, change styles, colors, icons and more with the ease.
version: 0.0.2
homepage: https://github.com/deb-sahu/top-snackbar

environment:
  sdk: '>=3.3.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
